### ISSUE TITLE
Expose Create table function ==> returning the string query

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#29]
We need function to have the query to build the table that we need.
It s going to be very useful, because you are prefixing table name now.
This string is going to be used by the Nathan data release tools

**Comment by crufter** [comment]
This is in master now, here is how you can use it:

(Assuming package is imported under name c)

```
tbl.(*c.T).CreateStatement()
tbl.(*c.OneToOneT).CreateStatement()
tbl.(*c.OneToManyT).CreateStatement()
tbl.(*c.TimeSeriesT).CreateStatement()
tbl.(*c.TimeSeriesBT).CreateStatement()
```

Depending on which table you are using. It is intentionally not in the interface and it is intentionally a bit hard to access, because the end users should not use this function, it is only for the builders of tooling.

**Comment by jcampan** [comment]
It s not working when i m using a gocql.UUID.

panic: Unsupported type gocql.UUID

**Comment by crufter** [comment]
That is unrelated to this issue though. Can we close this? Let's create an other issue for supporting the gocql.UUID type.

**Comment by jcampan** [comment]
ok
