### ISSUE TITLE
Consider changing the names of tables

### ISSUE THREAD

**Issue by crufter** [gocassa/gocassa#42]
In particular, I dislike 'OneToOne' and 'OneToMany'. Will post suggestions later.

**Comment by jcampan** [comment]
Ok, for OnetoOne, I would propose Entity or staticTable.
OneToMany ==> DynamicTable

**Comment by chrusty** [comment]
I spoke to Andreas about this, and after explaining the idea behind this naming-schema I think he's come around. It at least deserves further explanation, but the main point was to explain the RELATIONSHIP between the key(s) and value(s).
- OneToOne: 1 key to 1 object
- OneToMany: 1 key to MANY objects
- OneToManyTs: 1 key to MANY objects, ordered (and queried) by TIME
- SomeToMany: SOME composite key-components to MANY objects

I still think this is the most clear way to name these things, since all of the recipes are distinguished by the type of index they offer us.

**Comment by chrusty** [comment]
I can live with time-series instead of one-to-manyTS, but timeseriesB could do with a better name.

**Comment by crufter** [comment]
I agree TimeSeriesB is really bad.

Just throwing some ideas around:

| Old name | New name | Description |
| --- | --- | --- |
| OneToOne | Crud | CRUD |
| OneToMany | Eq | Can list rows based on == on a field |
| TimeSeries | TimeSeries | Can list rows based on <=, => on a time field, optimized for large number of rows |
| TimeSeriesB | EqTimeSeries | Can list rows based on == on a field and <=, => on a time field, optimized for large number of rows |

(OR: EqList, TimeSeriesList, EqTimeSeriesList)

So CRUD is implied everywhere, CRUD is called how it's called because that is all it can do, and the other tables are called by something which conveys their query capabilities.

By querying I mean something which returns more than 1 result, unlike Read.

**Comment by jcampan** [comment]
For now I will see
OneToOne : one key, one row
OneToMany : one key, many rows
Timeseries : timeseries
OneToTimeseries : one key, oneTimeserie.

These names are from an Data modelling perspective, i m not sure if they make sense from an Developer perspective.

**Comment by andreas** [comment]
|  |  |
| --- | --- |
| OneToOne | Thing |
| OneToMany | ThingWithSecondaryIndex |
| TimeSeries | TimeSeries |
| TimeSeriesB | TimeSeriesWithSecondaryIndex |

They are too verbose though :(

**Comment by crufter** [comment]
Just correcting myself: Eq for OneToMany does not make sense since it can support Between as well.
I love the `Thing`, @andreas.

http://www.imdb.com/title/tt0084787/

**Comment by braceta** [comment]
@crufter a more well known and more understandable name for OneToOne is KeyValue

**Comment by jcampan** [comment]
@andreas SecondaryIndex is not nice because it have an other meaning in Cassandra. I would like to avoid confusion with real secondary index.

Whats about that ?

KeyRow: you give one key, you have one row 
KeyList : you give one key, you have a list of row
Timeseries ; it s a global time series 
KeyTimeseries : you give a key, you have a time series

**Comment by crufter** [comment]
Done.
