### ISSUE TITLE
Rename the "SET" method to "REPLACE"

### ISSUE THREAD

**Issue by chrusty** [gocassa/gocassa#52]
"SET" doesn't give the full picture of what it actually does, which (when using an object) will completely overwrite any previous data.

"REPLACE" tells the whole story.

**Comment by crufter** [comment]
I do agree Replace is more descriptive for 'Update'. I decided against using it instead of `Set` because it is a bit unconventional and long(er than `Set`). I would trust the programmers to read a 2X1 liner documentation above the `Set` and `Update` methods or use common sense and realize that from the library point of view there is no difference between a struct literal containing a field with default values versus a struct literal not containing the field.

There is also the problem of `Replace` might be confusing when you are creating values - you do not replace anything. `Set` nicely describes the idempotency.

Let's see what we all think.

**Comment by jcampan** [comment]
I agree this crufter on this point. Set with a struct  is good enough .
