### ISSUE TITLE
Support for pagination?

### ISSUE THREAD

**Issue by chrusty** [gocassa/gocassa#57]

**Comment by crufter** [comment]
OneToMany supports pagination (with the combination of startId and limit), and in the timeSeries package pagination is done by moving the window of time in the query - simply because we expect the user to always request a time window which will produce a results set with a reasonable latency.

The Raw CQL table at the moment requires users to incorporate the paging into the query itself - this could be potentially helped by a mechanism which recognises and changes the query based on an artificially created 'lastId' which would be a combination of all the clustering column values.

**Comment by crufter** [comment]
@chrusty I am closing this unless you talk specifically about the mentioned feature in the Raw CQL table.

**Comment by postatum** [comment]
Hi @crufter.

Can you give me an advice please, how to do pagination using primary key in Raw CQL table at the moment?
I had no chance to filter on PK field using `gocassa.GT` because it says `Only EQ and IN relation are supported on the partition key (unless you use the token() function)` and I can't find any signs of `token` function in `gocassa`.

Thanks in advance!
