### ISSUE TITLE
Table name generator creates long table names

### ISSUE THREAD

**Issue by mattheath** [gocassa/gocassa#79]
When using the table helpers the table name is generated by contatenating various strings. Unfortunately even with short names for the various fields this can easily create table names which are longer than the 48 character maximum - giving the following error on `Create()`: `Column family names shouldn't be more than 48 characters long`.

Happens here:
https://github.com/hailocab/gocassa/blob/02f233ec3d3e1d0fd18d88929f286cbf8a4bc80d/keyspace.go#L97-L100

``` go
t: k.table(fmt.Sprintf("%s_multiTimeSeries_%s_%s_%s_%s", name, indexField, timeField, idField, bucketSize.String()), row, m, Keys{
    PartitionKeys:     []string{indexField, bucketFieldName},
    ClusteringColumns: []string{timeField, idField},
}).(*t),
```

I can't see any way to continue to override this naming while continuing to use the receipe tables? Happy to submit a patch, any suggestions on approach, or am I missing something?

**Comment by crufter** [comment]
I think the best is to shorten table types to:
- map -> m
- multimap -> mm
- timeseries -> ts
- multitimeseries -> mts

The could be left out entirely, but I am afraid that there will be recipes with same partition keys/clustering columns combination with different characteristics.

This is a breaking change so if we want to do it we should do it ASAP.

**Comment by obeattie** [comment]
I ran into this too last week. I thought we agreed to truncate table names when they are too long? We will need to do this even if we shorten the table type part.

**Comment by mattheath** [comment]
Yeah this would be a breaking change. I'd also suggest removing the time bucket duration - is this necessary? Separately it would be nice to be able to specify a manual name, which would also allow easier migration - I added temporary methods to override the automatic naming [here](https://github.com/b2aio/gocassa/compare/master...b2aio:tablenames)

**Comment by crufter** [comment]
@mattheath I was trying to follow a rule which says 'no two tables with different settings should have the same name' - even if their name is identical. This is because I want to use the same table name for different query patterns - it is easy to see how "transactions_multimap_sellerid_saleid" and "transactions_multimap_customerid_saleid" refers to the same table ("transactions"), but with different ways of accessing it.

This not only makes for a warm feeling in my tummy but also allows us to add a feature later which can maintain data across tables with the same (high level, not internal) name. So primarily the reason to encode all the partition keys - clustering columns information in the internal table name is to avoid collisions (just look at how "transactions_multimap_sellerid_saleid" and "transactions_multimap_customerid_saleid" would collide without it).

An alternative solution is to let people name their tables however they want and have a manual way of marking tables as 'describing the same entity' in case someone wants the library to maintain data across tables.

Pros:
- Easy to avoid the problem this issue is about

Cons:
- It might make things harder for OP teams, since we lose uniformity, and the structure of the table is no longer obvious just by looking at the name
- We have to manually cross link the tables to use the aforementioned feature.

**Comment by obeattie** [comment]
The only way we're really going to guarantee uniqueness within length constraints is to hash the table config… but then we'll end up with gross table names :cry:

**Comment by crufter** [comment]
@obeattie We do guarantee uniqueness with the current design AFAIK, but it produces long names.

**Comment by obeattie** [comment]
Yes, I mean that even by shortening the internal type names, it still doesn't guarantee it's short enough (given it's dependent on the user's column names). The only way to really do this within the length constraints, is to hash.

**Comment by crufter** [comment]
Fieldnames can be shortened with struct tags: https://github.com/hailocab/gocassa/pull/75

**Comment by mattheath** [comment]
> An alternative solution is to let people name their tables however they want and have a manual way of marking tables as 'describing the same entity' in case someone wants the library to maintain data across tables.

Yeah i'd like to be able to do this. Some of our tables are exceptionally long!

**Comment by mattheath** [comment]
Thoughts on changing the function signature for the table creators to be variadic with an optional TableOptions param?

eg.

``` go
type TableOptions struct{
    TableName string
    // ... other config options eg. high level name
}

func (k *k) TimeSeriesTable(name, timeField, idField string, bucketSize time.Duration, row interface{}, opts ...TableOptions) TimeSeriesTable {
    options := mergeTableOptions(opts...)

    // Construct a CQL table name if not provided
    if options.TableName == "" {
        options.TableName = fmt.Sprintf("%s_timeSeries_%s_%s_%s", name, timeField, idField, bucketSize.String())
    }

    // previous behaviour
    return &timeSeriesT{
        t: k.table(options.TableName, row, m, Keys{
        //...
    }
}
```

**Comment by mattheath** [comment]
Opened a PR for the above (#82) with some sample code for discussion

**Comment by crufter** [comment]
This can be worked around with #85

**Comment by mattheath** [comment]
:+1:
