### ISSUE TITLE
Times series recipe should use a non functional uniq id

### ISSUE THREAD

**Issue by hailobackup** [gocassa/gocassa#9]
I think that the uniq id in this recipe should be always an uuid and not 'a la carte'.
It would prevent mistake, non optimal solution and avoid to have 10 sub recipe.

Let s have a talk about it

**Comment by jcampan** [comment]
its me

**Comment by chrusty** [comment]
I agree. This is time-series and should be queried by time-ranges. Some kind of user-specified object-ID can theoretically lead to clashes and data loss, better to keep this completely random.

**Comment by chrusty** [comment]
Perhaps this should become an OPTIONAL time-series feature for people who actually have a need for a user-specified unique ID, but the default should be TIMESTAMP+UUID.

**Comment by crufter** [comment]
At the moment the timeSeries interface completely mirrors oneToMany, hiding the unique ID would mean we lose the ability to identify and do CRUD on an exact row when using timeSeries.

> Some kind of user-specified object-ID can theoretically lead to clashes and data loss

Supplying non-unique values as unique IDs will definitely lead to 'clashes and data loss', that is not specific to this recipe.

If I understand your point correctly, you worry about people using IDs of objects as timeSeries unique IDs, which will not necessarily be unique in a the timeSeries, table, such as:

```
type Event {
   UserId                 string
   WhatHappened   string
   WhenHappened  time.Time 
}

userEvents := keySpace.TimeSeries("event", "WhenHappened", "UserId")
```

The above example is obviously wrong, because since one user can have more than one events in the timeSeries table, the scenario you fear will indeed arise.

It is easy to see how the correct solution looks like the following:

```
type Event {
   EventId               string
   UserId                string
   WhatHappened  string
   WhenHappened time.Time 
}

userEvents := keySpace.TimeSeries("event", "WhenHappened", "EventId")
```

I believe the probability of the aforementioned scenario happening is low enough, and it can be corrected by code reviews, education, and documentation thus it does not warrant deviating the timeSeries interface from the other recipes, limiting the abilities of the user, spending time on implementation and increasing the complexity of the timeSeries recipe.

Also, please paste here the new interface you want to see so we can discuss it.

Summoning @obeattie and @andreas here for additional input.

**Comment by obeattie** [comment]
Sorry, I'm struggling to keep up. Can someone summarise concisely what the actual concern is here, and what the proposed solution is? I understand it has something to do with user-supplied object IDs in the context of the timeseries recipe(s)…

**Comment by crufter** [comment]
@obeattie @chrusty and @jcampan wanted to hide the UUID under the hood because they were afraid of people supplying nonunique values. But that means no CRUD in timeSeries.

We just agreed to solve this with having and promoting conventions to avoid this, so I am closing it for the moment. @chrusty @jcampan reopen this if you object.
